#
# Module manifest for module 'SecretsManagement.BitLocker'
#
# Generated by: erikgraa
#
# Generated on: 05/15/2025
#

@{
    ModuleVersion = '0.2505.2'
    CompatiblePSEditions = @('Core', 'Desktop')
    GUID = 'aa148291-88a1-4cf7-b3cf-216f7ede5661'
    Author = 'erikgraa'
    Copyright = 'Copyright (c) 2025 erikgraa, licensed under the MIT License.'
    Description = 'A SecretManagement Vault extension for BitLocker recovery passwords stored in Active Directory.'
    PowerShellVersion = '5.1'

    NestedModules = @('./SecretManagement.BitLocker.Extension')

    RequiredModules = @('Microsoft.Powershell.SecretManagement')

    PrivateData = @{
        PSData = @{
            Tags = @(
                'ActiveDirectory', 'BitLocker', 'PowerShell', 'PowerShell-Core', 'Secret',
                'SecretManagement', 'Vault', 'VaultExtension', 'Microsoft'
            )

            ExternalModuleDependencies = @('ActiveDirectory')            

            ProjectUri     = 'https://github.com/erikgraa/SecretManagement.BitLocker'
            License        = 'https://github.com/erikgraa/SecretManagement.BitLocker/blob/main/LICENSE'
            IconUri        = 'https://raw.githubusercontent.com/erikgraa/SecretManagement.BitLocker/refs/heads/main/images/logo.png'
            ReleaseNotes   = 'https://github.com/erikgraa/SecretManagement.BitLocker'
        }
    }
}